# Generated by Django 5.2.6 on 2025-09-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_rescue_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='modified_date',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
