# Generated by Django 5.2.6 on 2025-09-08 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_rescue_app', '0003_notification_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pet_rescue_app.pet'),
        ),
        migrations.AddField(
            model_name='notification',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pet_rescue_app.petreport'),
        ),
    ]
