# Generated by Django 5.2.6 on 2025-09-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_rescue_app', '0007_rewardpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petreport',
            name='pet_status',
            field=models.CharField(choices=[('Lost', 'Lost'), ('Found', 'Found'), ('Adopted', 'Adopted'), ('Rejected', 'Rejected')], max_length=20),
        ),
    ]
