# Generated by Django 5.2.6 on 2025-09-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_rescue_app', '0008_alter_petreport_pet_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petreport',
            name='pet_status',
            field=models.CharField(choices=[('Lost', 'Lost'), ('Found', 'Found'), ('Adopted', 'Adopted')], max_length=20),
        ),
        migrations.AlterField(
            model_name='petreport',
            name='report_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Resolved', 'Resolved'), ('Reunited', 'Reunited')], default='Pending', max_length=20),
        ),
    ]
