# Generated by Django 5.2.6 on 2025-09-24 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_rescue_app', '0010_feedbackstory'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('Sighting', 'Sighting'), ('Reclaim', 'Reclaim'), ('Adoption', 'Adoption')], max_length=20)),
                ('message', models.TextField()),
                ('report_status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Reunited', 'Reunited'), ('Resolved', 'Resolved')], default='Pending', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('pet_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reports', to='pet_rescue_app.petreport')),
                ('pet_report_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
